# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 429c777eed1add182a9df53c90f1da10a174a8430756d6c99cf79c1d649d4af8058bd092dd084426241dde3742734c2086b94b3d6a553e3a034a9c033370cfa3

test:
  secret_key_base: 3af913932002e0312e0875b61181e0838a8afc82ab9881286aecd0c86657d61816b619da6d5b01d6f2dd4470a22ec5fac33bfdf504956de26ac47fa0f81967fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
